services:
  - type: web
    name: diploma-generator
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --max-requests 1000 --max-requests-jitter 50 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONMALLOC
        value: "malloc"
      - key: MALLOC_ARENA_MAX
        value: "2"
    plan: free
    healthCheckPath: /
    autoDeploy: true 