services:
  - type: web
    name: diploma-generator
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 